[client]
showErrorDetails = false
toolbarMode = "minimal"
maxMessageSize = 200

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
headless = true
port = 8501

[logger]
level = "info"

[theme]
primaryColor = "#1f6e58"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#262626"
font = "sans serif"
